project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  title: "Bitácora Práctica de Restauración de Ecosistemas"
  navbar:
    search: true
    left:
      - text: Prácticos
        href: practicosIntro.qmd

      - text: Metodología
        href: meto.qmd

    right:
      - text: Agradecimientos
        href: agra.qmd

  sidebar: 
    style: floating
    search: true
    contents: 
      - text: "Prácticos"
        href: practicosIntro.qmd

        contents: 
          - text: "13 de Agosto"
            href: prac1_13-08-24.qmd

          - text: "20 de Agosto"
            href: prac2_20-08-24.qmd

          - text: "27 de Agosto"
            href: prac3_27-08-24.qmd
          
          - text: "03 de Septiembre"
            href: prac4_03-09-24.qmd

          - text: "24 de Septiembre"
            href: prac5_24-09-24.qmd

          - text: "15 de Octubre"
            href: prac6_15-10-21.qmd

          - text: "22 de Octubre"
            href: prac7_22-10-24.qmd

          - text: "29 de Octubre"
            href: prac8_29-10-24.qmd

          - text: "19 de Noviembre"
            href: prac9_19-11-24.qmd

format:
  html:
    lang: es
    theme: cosmo
    css: styles.css
    toc: true




